---
- name: Testing AAP Project Creation
  hosts: controller
  remote_user: automation
  tasks:

    - name: Display test message
      ansible.builtin.debug:
        msg: "This is a test from {{ inventory_hostname }}!"
